"""initial postgres schema

Revision ID: 85aa80937ad3
Revises: 
Create Date: 2026-08-03 13:59:24.657480
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85aa80937ad3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', name='uq_import_source_hash')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('identity', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_restaurants_normalized_name'), 'restaurants', ['normalized_name'], unique=False)
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(length=160), nullable=False),
    sa.Column('preference_state', sa.JSON(), nullable=False),
    sa.Column('active_restaurant', sa.String(length=160), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_table('menu_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'version', name='uq_menu_version')
    )
    op.create_index('idx_active_menu', 'menu_versions', ['restaurant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_menu_versions_is_active'), 'menu_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_menu_versions_restaurant_id'), 'menu_versions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_menu_versions_source_hash'), 'menu_versions', ['source_hash'], unique=False)
    op.create_table('review_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_review', 'review_runs', ['restaurant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_review_runs_is_active'), 'review_runs', ['is_active'], unique=False)
    op.create_index(op.f('ix_review_runs_restaurant_id'), 'review_runs', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_review_runs_status'), 'review_runs', ['status'], unique=False)
    op.create_table('menu_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'position', name='uq_menu_category_position')
    )
    op.create_index(op.f('ix_menu_categories_menu_id'), 'menu_categories', ['menu_id'], unique=False)
    op.create_table('review_aspects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('aspect', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_aspects_review_run_id'), 'review_aspects', ['review_run_id'], unique=False)
    op.create_table('review_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=80), nullable=False),
    sa.Column('aspect', sa.String(length=40), nullable=False),
    sa.Column('polarity', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_evidence_review_run_id'), 'review_evidence', ['review_run_id'], unique=False)
    op.create_table('review_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sources_review_run_id'), 'review_sources', ['review_run_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('spice_min', sa.Integer(), nullable=True),
    sa.Column('spice_max', sa.Integer(), nullable=True),
    sa.Column('spice_adjustable', sa.Boolean(), nullable=False),
    sa.Column('semantic_profile', sa.JSON(), nullable=False),
    sa.Column('semantic_confidence', sa.Float(), nullable=False),
    sa.Column('semantic_source', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_normalized_name'), 'menu_items', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_menu_items_role'), 'menu_items', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_role'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_normalized_name'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_review_sources_review_run_id'), table_name='review_sources')
    op.drop_table('review_sources')
    op.drop_index(op.f('ix_review_evidence_review_run_id'), table_name='review_evidence')
    op.drop_table('review_evidence')
    op.drop_index(op.f('ix_review_aspects_review_run_id'), table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_index(op.f('ix_menu_categories_menu_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_review_runs_status'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_restaurant_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_is_active'), table_name='review_runs')
    op.drop_index('idx_active_review', table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_menu_versions_source_hash'), table_name='menu_versions')
    op.drop_index(op.f('ix_menu_versions_restaurant_id'), table_name='menu_versions')
    op.drop_index(op.f('ix_menu_versions_is_active'), table_name='menu_versions')
    op.drop_index('idx_active_menu', table_name='menu_versions')
    op.drop_table('menu_versions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_restaurants_normalized_name'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
